feat: add glot plugin
koishijs/koishi-plugin-tools pull request #1
Opened 2021-12-03 16:09 UTC by Anillc

2021-12-03 17:19 UTC, Shigma requested changes

2021-12-03 17:19 UTC, Shigma commented on README.md
> +### 配置项: registerSubcommands
1. 下面的代码实现，两种写法都叫 subcommand，这个配置项名字不对
2. 个人角度非常建议你统一成一种，不要让用户设置，毕竟这里需求挺单一的
3. 如果非要有 subcommands 这个配置项，我觉得可以是这样：
    - 不配置 subcommands 时的行为：只允许 `glot -l lang code` 的调用方式
    - 配置 subcommands 时的行为：subcommands 是一个数组或者 true
      - 如果是 true：所有支持的语言都会注册为子指令
      - 如果是数组：数组中的语言会注册为子指令（其余的仍然可以使用上述调用方式）

2021-12-03 17:19 UTC, Shigma commented on src/glot.ts
> +const languages = ["assembly","ats","bash","c","clojure","cobol","coffeescript","cpp","crystal","csharp","d","elixir","elm","erlang","fsharp","go","groovy","haskell","idris","java","javascript","juli
这行稍微 format 一下，改单引号，逗号后面加个空格即可

2021-12-03 17:19 UTC, Shigma commented on src/glot.ts
> +const languages = ["assembly","ats","bash","c","clojure","cobol","coffeescript","cpp","crystal","csharp","d","elixir","elm","erlang","fsharp","go","groovy","haskell","idris","java","javascript","juli
也可以像上面 readme 里面一样分个三行

2021-12-03 17:19 UTC, Shigma commented on src/glot.ts
> +
这里可以加个 `export const name = 'glot'`

2021-12-04 06:19 UTC, Shigma commented on src/glot.ts
> +  ctx.command('glot <code:rawtext>', `运行代码\n支持的语言: ${languages.join(', ')}`)
https://koishi.js.org/api/core/command.html#cmd-usage-text

2021-12-04 06:19 UTC, Shigma commented on src/glot.ts
> +  defalutLanguage: string
typo

2021-12-04 06:19 UTC, Shigma commented on src/glot.ts
> +    const res = await axios.post(`https://glot.io/api/run/${language}/latest`,{
建议使用 ctx.http.post() 代替，这样可以利用 koishi 的 proxy 配置

2021-12-04 07:20 UTC, Shigma commented on src/glot.ts
> +    return await http.post(`https://glot.io/api/run/${language}/latest`, {
在初始化的时候

```ts
http = ctx.http.extend({
  headers: {
    'Authorization': `Token ${token}`,
  },
})
```

这样只需要传三个参数就行了。

2021-12-04 07:30 UTC, Anillc commented on src/glot.ts
> +    return await http.post(`https://glot.io/api/run/${language}/latest`, {
虽然应该不会被复用，但是如果不注意的话其他地方传入普通的 `Quester` 就会请求失败，所以感觉把 `token` 传进函数里要好些。

2021-12-04 08:02 UTC, Shigma commented on src/glot.ts
> +    return await http.post(`https://glot.io/api/run/${language}/latest`, {
我是说插件初始化的时候

```ts
export function apply(ctx: Context) {
  const http = ctx.http.extend()
}
```

你现在 run 方法耦合度比较高，我其实甚至建议你把 `https://glot.io/api/` 都作为 endpoint 写进 extend 里面。就算以后做多次请求也非常方便。

2021-12-04 08:44 UTC, Anillc commented on src/glot.ts
> +    return await http.post(`https://glot.io/api/run/${language}/latest`, {
修改了，不过感觉这样也不是很好。glot 的 run api 只有三个接口，只有这一个接口需要 token 而且是 post，另外语言这个参数也是写在 url 里的，所以不好抽更多代码出来了

2021-12-04 11:07 UTC, Shigma approved these changes

2021-12-04 11:08 UTC, Shigma commented on src/glot.ts
> +    return await http.post(`https://glot.io/api/run/${language}/latest`, {
其实也只是一种开发风格而已。就这样吧。

2021-12-04 16:03 UTC, merged